Admin product
shin72mican/shopping pull request #3
Opened 2024-05-02 03:02 UTC by shin72mican

商品管理機能
- 一覧ページ
- 新規登録処理
- 詳細ページ
- 編集ページ
- 編集処理
- 削除処理

2024-05-02 03:04 UTC, shin72mican commented
商品管理機能でプルリクを送りました。
お時間があるときで大丈夫ですのでご確認のほどよろしくお願いします。

2024-05-09 13:56 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		model.addAttribute("product", products.get(0));
[例外](https://docs.oracle.com/javase/jp/7/api/java/lang/ArrayIndexOutOfBoundsException.html)が発生する可能性があります。

2024-05-09 13:56 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/error/ProductErrorCheckService.java
> +	public List<String> errorCheck(Products product, MultipartFile productImage) {
引数 `Products product` の `description` の文字長チェックを追加お願いします。

データベースの文字長を超えていても登録しようとして
想定しない例外(制御できていない例外)が発生するためです。

2024-05-09 13:56 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/error/ProductErrorCheckService.java
> +			String extension = originalFileName.substring(originalFileName.lastIndexOf("."));
ファイル名に `.` が無い場合、[例外](https://docs.oracle.com/javase/jp/7/api/java/lang/StringIndexOutOfBoundsException.html)が発生します。

`String.lastIndexOf(String)` は存在しない文字の場合は-1を返すため、
チェックを追加する場合の基準としてください。

2024-05-09 13:56 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/image/ProductImageService.java
> +		UUID uuid = UUID.randomUUID();
システムで一意な文字列をシンプルに作成する方法の一つとしてUUIDを使うことがあり、
暫定でなくても差し支えないと思います。

システムで一意な文字列作成の候補として、
日時をミリ秒まで含めた文字列を使うこともあります。

2024-05-09 13:56 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/error/ProductErrorCheckService.java
> +				errors.add("jpg, jpeg, pngファイルでしか保存することができません");
登録可能なファイル拡張子を変化させる場合、
エラーメッセージも併せて変更する必要があります。

対応は不要ですが、動的にメッセージを生成する方法を検討してみてください。

2024-05-09 14:00 UTC, hara-y-illmatics commented
フィードバックしました。
確認お願いします。

2024-05-10 07:44 UTC, hara-y-illmatics requested changes
フィードバックしました。
確認お願いします。

2024-05-11 04:32 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminCategoryController.java
> +		categories = categoriesMapper.findSearch(name, sortType, sortDirection, displayCount, currentPage);
productsMapper.find()自体がAdminProductControllerの編集ページ179行目で単一データ取得で使っているため、別の名前でfindSearchで使っているためご確認お願いしたいです。

2024-05-11 05:04 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminCategoryController.java
> +		categories = categoriesMapper.findSearch(name, sortType, sortDirection, displayCount, currentPage);
補足します。

* メソッド名に find と search の両方(どちらも探すという意味合い)を使わない方が望ましい。
* `find` のみ等にしてメソッド名が重複しないようにする。

上記を踏まえてメソッドの目的に沿った名称にすることが好ましいという意味合いです。
例) 検索条件が単一であり、カテゴリー名で検索するメソッドは `findByName` とする。

今回の場合は検索条件(メソッドの引数)が複数のため、 `findByCondition` 等を例として挙げます。

2024-05-11 05:45 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminCategoryController.java
> +		categories = categoriesMapper.findSearch(name, sortType, sortDirection, displayCount, currentPage);
findIndex -> findByConditionに変更しました。

2024-05-11 05:54 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		model.addAttribute("product", products.get(0));
データがない場合、403エラーページを表示するように変更しました。
編集ページも同様にデータがないとき、403ページを表示するように変更しました。

2024-05-11 05:55 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		int pageCount = productsMapper.findSearchCount(categoryId, name, price, standard);
すみません、コントローラーの処理共通化対象が具体的に理解できていないので確認したいのですが、Serviceでまとめるということでしょうか？

2024-05-11 10:36 UTC, 72-mikan commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		model.addAttribute("product", products.get(0));
詳細画面と同時に403エラーを表示するように変更を加えました。
ご確認のほどよろしくお願いします。

2024-05-11 10:37 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		model.addAttribute("product", products.get(0));
詳細画面と同時に403エラーを表示するように変更を加えました。
ご確認のほどよろしくお願いします。

2024-05-13 02:05 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/error/ProductErrorCheckService.java
> +	public List<String> errorCheck(Products product, MultipartFile productImage) {
255文字を超える際、エラーが表示されるように修正しました。

2024-05-13 05:18 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +			@RequestParam(name = "price", defaultValue = "") Long price,
テキストボックスをtype="text"に変更し、Stringで受け取ってから以下の例外処理を追加しました。
```
Long price;
try {
	price = Long.parseLong(formPrice);
} catch (NumberFormatException e) {
	errors.add("価格は数値でしか登録することができません");
	price = 0L;
}
```

2024-05-13 05:56 UTC, hara-y-illmatics reviewed
現時点までのコミットを確認済みです。

2024-05-13 06:27 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/error/ProductErrorCheckService.java
> +			String extension = originalFileName.substring(originalFileName.lastIndexOf("."));
以下の例外処理を加えました。
```
// ファイル名取得
String originalFileName = productImage.getOriginalFilename();
// ファイル拡張子取得
String extension;
try {
	extension = originalFileName.substring(originalFileName.lastIndexOf("."));
} catch(StringIndexOutOfBoundsException e) {
	extension = "";				
}
```

2024-05-13 06:32 UTC, shin72mican commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		int pageCount = productsMapper.findSearchCount(categoryId, name, price, standard);
承知しました。
ご確認ありがとうございます。
後ほど修正しておきます。

2024-05-13 06:50 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +			@RequestParam(name = "price", defaultValue = "") Long price,
提示いただいた修正内容で差し支えありません。

以下、対応不要ですが補足です。
ただし、バリデーションの実装方法は対象が数値なら

* 半角数字のみ（場合によっては小数点、プラス記号、マイナス記号を許容）、のように文字種が限定されていなければエラー
* 対象を数値化しようとして例外が発生すればエラー

という2種類がよくみられる方法です。

2024-05-13 06:52 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/service/admin/error/ProductErrorCheckService.java
> +			String extension = originalFileName.substring(originalFileName.lastIndexOf("."));
差し支えありません。

こちらも他のバリデーション方法についての補足と同様です。

2024-05-13 07:33 UTC, hara-y-illmatics commented on shopping-app/src/main/java/jp/co/illmatics/apps/shopping/controller/AdminProductController.java
> +		int pageCount = productsMapper.findSearchCount(categoryId, name, price, standard);
こちら対応不要です。
そういったリファクタリングが可能ということです。

2024-05-13 07:35 UTC, hara-y-illmatics approved these changes
レビュー完了です。

2024-05-13 07:35 UTC, merged